name:  deploy 

on: 
 push:
  branches:
    - master

jobs:
    build:
      runs-on: ubunutu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create a file
        run: |
         mkdir -p local/testing
         
      - name: install docker..
        run: |
              apt-get -y install dnf-plugins-core
              apt-get config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo 
              apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Start proccess.
        run: |
          sudo systemctl enable --now docker 

