name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifest
        run: |
          kubectl apply -f workflow/local/Untiled.yaml
